[package]
name = "gl_constants"
description = "Declares OpenGL and OpenGL ES enumerated constant values."
repository = "https://github.com/Lokathor/gl_constants"
version = "0.1.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
gl_types = "0.1.0"
